[package]
name = "memflow-pcileech"
version = "0.1.5"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"
description = "qemu procfs connector for leechcore/pcileech"
documentation = "https://docs.rs/memflow-pcileech"
readme = "../README.md"
homepage = "https://memflow.github.io"
repository = "https://github.com/memflow/memflow-pcileech"
license-file = "../LICENSE"
keywords = [ "memflow", "introspection", "memory" ]
categories = [ "api-bindings", "memory-management", "os" ]

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
memflow = { git = "https://github.com/memflow/memflow", branch = "next", features = ["plugins", "memmapfiles"] }
log = { version = "0.4", default-features = false }
leechcore-sys = { path = "../leechcore-sys" }

[dev-dependencies]
clap = "2.33"
simple_logger = "1.0"
memflow-win32 = { git = "https://github.com/memflow/memflow-win32", branch = "main" }

[[example]]
name = "read_phys"
path = "examples/read_phys.rs"

[[example]]
name = "ps_win32"
path = "examples/ps_win32.rs"

[[example]]
name = "ps_inventory"
path = "examples/ps_inventory.rs"
