[package]
name = "leechcore-sys"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"
readme = "../README.md"
license-file = "../LICENSE"

links = "leechcore"

[dependencies]
ctor = "0.1"

[build-dependencies]
cc = "1.0.62"
bindgen = "0.55"
pkg-config = "0.3"
