[package]
name = "leechcore-sys"
version = "0.2.0-beta5"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"
readme = "../README.md"
license = "GPL-3.0"

links = "leechcore"

[dependencies]
ctor = "0.1"

[build-dependencies]
cc = "1.0"
bindgen = "^0.60.1"
pkg-config = "0.3"
